#include <stdio.h>
#include "ast.h"
#include "stack.h"

#define PROLOG do {printf(".IFJcode24");} while(0)

#define MOVE(var, symb) do {printf("\nMOVE %s %s", var, symb);} while(0)
#define CREATEFRAME do {printf("\nCREATEFRAME");} while(0)
#define PUSHFRAME do {printf("\nPUSHFRAME");} while(0)
#define POPFRAME do {printf("\nPOPFRAME");} while(0)
#define DEFVAR(var) do {printf("\nDEFVAR %s", var);} while(0)
#define CALL(label) do {printf("\nCALL %s", label);} while(0)
#define RETURN do {printf("\nRETURN");} while(0)

#define PUSHS(symb) do {printf("\nPUSHS %s", symb);} while(0)
#define POPS(var) do {printf("\nPOPS %s", var);} while(0)
#define CLEARS do {printf("\nCLEARS");} while(0)

#define ADD(var, symb1, symb2) do {printf("\nADD %s %s %s", var, symb1, symb2);} while(0)
#define SUB(var, symb1, symb2) do {printf("\nSUB %s %s %s", var, symb1, symb2);} while(0)
#define MUL(var, symb1, symb2) do {printf("\nMUL %s %s %s", var, symb1, symb2);} while(0)
#define DIV(var, symb1, symb2) do {printf("\nDIV %s %s %s", var, symb1, symb2);} while(0)
#define IDIV(var, symb1, symb2) do {printf("\nIDIV %s %s %s", var, symb1, symb2);} while(0)
#define ADDS(var, symb1, symb2) do {printf("\nADDS %s %s %s", var, symb1, symb2);} while(0)
#define SUBS(var, symb1, symb2) do {printf("\nSUBS %s %s %s", var, symb1, symb2);} while(0)
#define MULS(var, symb1, symb2) do {printf("\nMULS %s %s %s", var, symb1, symb2);} while(0)
#define DIVS(var, symb1, symb2) do {printf("\nDIVS %s %s %s", var, symb1, symb2);} while(0)
#define IDIVS(var, symb1, symb2) do {printf("\nIDIVS %s %s %s", var, symb1, symb2);} while(0)
#define LT(var, symb1, symb2) do {printf("\nLT %s %s %s", var, symb1, symb2);} while(0)
#define GT(var, symb1, symb2) do {printf("\nGT %s %s %s", var, symb1, symb2);} while(0)
#define EQ(var, symb1, symb2) do {printf("\nEQ %s %s %s", var, symb1, symb2);} while(0)
#define LTS(var, symb1, symb2) do {printf("\nLTS %s %s %s", var, symb1, symb2);} while(0)
#define GTS(var, symb1, symb2) do {printf("\nGTS %s %s %s", var, symb1, symb2);} while(0)
#define EQS(var, symb1, symb2) do {printf("\nEQS %s %s %s", var, symb1, symb2);} while(0)
#define AND(var, symb1, symb2) do {printf("\nAND %s %s %s", var, symb1, symb2);} while(0)
#define OR(var, symb1, symb2) do {printf("\nOR %s %s %s", var, symb1, symb2);} while(0)
#define NOT(var, symb) do {printf("\nNOT %s %s", var, symb);} while(0)
#define ANDS(var, symb1, symb2) do {printf("\nANDS %s %s %s", var, symb1, symb2);} while(0)
#define ORS(var, symb1, symb2) do {printf("\nORS %s %s %s", var, symb1, symb2);} while(0)
#define NOTS(var, symb) do {printf("\nNOTS %s %s", var, symb);} while(0)
#define INT2FLOAT(var, symb) do {printf("\nINT2FLOAT %s %s", var, symb);} while(0)
#define FLOAT2INT(var, symb) do {printf("\nFLOAT2INT %s %s", var, symb);} while(0)
#define INT2CHAR(var, symb) do {printf("\nINT2CHAR %s %s", var, symb);} while(0)
#define STRI2INT(var, symb1, symb2) do {printf("\nSTRI2INT %s %s %s", var, symb1, symb2);} while(0)
#define INT2FLOATS(var, symb) do {printf("\nINT2FLOATS %s %s", var, symb);} while(0)
#define FLOAT2INTS(var, symb) do {printf("\nFLOAT2INTS %s %s", var, symb);} while(0)
#define INT2CHARS(var, symb) do {printf("\nINT2CHARS %s %s", var, symb);} while(0)
#define STRI2INTS(var, symb1, symb2) do {printf("\nSTRI2INTS %s %s %s", var, symb1, symb2);} while(0)

#define READ(var, type) do {printf("\nREAD %s %s", var, type);} while(0)
#define WRITE(symb) do {printf("\nWRITE %s", symb);} while(0)

#define CONCAT(var, symb1, symb2) do {printf("\nCONCAT %s %s %s", var, symb1, symb2);} while(0)
#define STRLEN(var, symb) do {printf("\nSTRLEN %s %s", var, symb);} while(0)
#define GETCHAR(var, symb1, symb2) do {printf("\nGETCHAR %s %s %s", var, symb1, symb2);} while(0)
#define SETCHAR(var1, symb1, symb2) do {printf("\nSETCHAR %s %s %s", var1, symb1, symb2);} while(0)

#define TYPE(var, symb) do {printf("\nTYPE %s %s", var, symb);} while(0)

#define LABEL(label) do {printf("\nLABEL %s", label);} while(0)
#define JUMP(label) do {printf("\nJUMP %s", label);} while(0)
#define JUMPIFEQ(label, symb1, symb2) do {printf("\nJUMPIFEQ %s %s %s", label, symb1, symb2);} while(0)
#define JUMPIFNEQ(label, symb1, symb2) do {printf("\nJUMPIFNEQ %s %s %s", label, symb1, symb2);} while(0)
#define JUMPIFEQS(label, symb1, symb2) do {printf("\nJUMPIFEQS %s %s %s", label, symb1, symb2);} while(0)
#define JUMPIFNEQS(label, symb1, symb2) do {printf("\nJUMPIFNEQS %s %s %s", label, symb1, symb2);} while(0)
#define EXIT(exit_code) do {printf("\nEXIT int@(exit_code)");} while(0)

#define AP(var) dyn_str_append_str(functions, var)
#define APPEND_MOVE(var, symb) do {AP("\nMOVE "); AP(var); AP(" "); AP(symb);} while(0)
#define APPEND_CREATEFRAME do {AP("\nCREATEFRAME");} while(0)
#define APPEND_PUSHFRAME do {AP("\nPUSHFRAME");} while(0)
#define APPEND_POPFRAME do {AP("\nPOPFRAME");} while(0)
#define APPEND_DEFVAR(var) do {AP("\nDEFVAR "); AP(var);} while(0)
#define APPEND_CALL(label) do {AP("\nCALL "); AP(label);} while(0)
#define APPEND_RETURN do {AP("\nRETURN");} while(0)

#define APPEND_PUSHS(symb) do {AP("\nPUSHS "); AP(symb);} while(0)
#define APPEND_POPS(var) do {AP("\nPOPS "); AP(var);} while(0)
#define APPEND_CLEARS do {AP("\nCLEARS");} while(0)

#define APPEND_ADD(var, symb1, symb2) do {AP("\nADD "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_SUB(var, symb1, symb2) do {AP("\nSUB "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_MUL(var, symb1, symb2) do {AP("\nMUL "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_DIV(var, symb1, symb2) do {AP("\nDIV "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_IDIV(var, symb1, symb2) do {AP("\nIDIV "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_ADDS(var, symb1, symb2) do {AP("\nADDS "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_SUBS(var, symb1, symb2) do {AP("\nSUBS "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_MULS(var, symb1, symb2) do {AP("\nMULS "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_DIVS(var, symb1, symb2) do {AP("\nDIVS "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_IDIVS(var, symb1, symb2) do {AP("\nIDIVS "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_LT(var, symb1, symb2) do {AP("\nLT "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_GT(var, symb1, symb2) do {AP("\nGT "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_EQ(var, symb1, symb2) do {AP("\nEQ "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_LTS(var, symb1, symb2) do {AP("\nLTS "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_GTS(var, symb1, symb2) do {AP("\nGTS "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_EQS(var, symb1, symb2) do {AP("\nEQS "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_AND(var, symb1, symb2) do {AP("\nAND "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_OR(var, symb1, symb2) do {AP("\nOR "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_NOT(var, symb) do {AP("\nNOT "); AP(var); AP(" "); AP(symb);} while(0)
#define APPEND_ANDS(var, symb1, symb2) do {AP("\nANDS "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_ORS(var, symb1, symb2) do {AP("\nORS "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_NOTS(var, symb) do {AP("\nNOTS "); AP(var); AP(" "); AP(symb);} while(0)
#define APPEND_INT2FLOAT(var, symb) do {AP("\nINT2FLOAT "); AP(var); AP(" "); AP(symb);} while(0)
#define APPEND_FLOAT2INT(var, symb) do {AP("\nFLOAT2INT "); AP(var); AP(" "); AP(symb);} while(0)
#define APPEND_INT2CHAR(var, symb) do {AP("\nINT2CHAR "); AP(var); AP(" "); AP(symb);} while(0)
#define APPEND_STRI2INT(var, symb1, symb2) do {AP("\nSTRI2INT "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_INT2FLOATS(var, symb) do {AP("\nINT2FLOATS "); AP(var); AP(" "); AP(symb);} while(0)
#define APPEND_FLOAT2INTS(var, symb) do {AP("\nFLOAT2INTS "); AP(var); AP(" "); AP(symb);} while(0)
#define APPEND_INT2CHARS(var, symb) do {AP("\nINT2CHARS "); AP(var); AP(" "); AP(symb);} while(0)
#define APPEND_STRI2INTS(var, symb1, symb2) do {AP("\nSTRI2INTS "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)

#define APPEND_READ(var, type) do {AP("\nREAD "); AP(var); AP(" "); AP(type);} while(0)
#define APPEND_WRITE(symb) do {AP("\nWRITE "); AP(symb);} while(0)

#define APPEND_CONCAT(var, symb1, symb2) do {AP("\nCONCAT "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_STRLEN(var, symb) do {AP("\nSTRLEN "); AP(var); AP(" "); AP(symb);} while(0)
#define APPEND_GETCHAR(var, symb1, symb2) do {AP("\nGETCHAR "); AP(var); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_SETCHAR(var1, symb1, symb2) do {AP("\nSETCHAR "); AP(var1); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)

#define APPEND_TYPE(var, symb) do {AP("\nTYPE "); AP(var); AP(" "); AP(symb);} while(0)

#define APPEND_LABEL(label) do {AP("\nLABEL "); AP(label);} while(0)
#define APPEND_JUMP(label) do {AP("\nJUMP "); AP(label);} while(0)
#define APPEND_JUMPIFEQ(label, symb1, symb2) do {AP("\nJUMPIFEQ "); AP(label); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_JUMPIFNEQ(label, symb1, symb2) do {AP("\nJUMPIFNEQ "); AP(label); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_JUMPIFEQS(label, symb1, symb2) do {AP("\nJUMPIFEQS "); AP(label); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_JUMPIFNEQS(label, symb1, symb2) do {AP("\nJUMPIFNEQS "); AP(label); AP(" "); AP(symb1); AP(" "); AP(symb2);} while(0)
#define APPEND_EXIT(exit_code) do {AP("\nEXIT "); AP(exit_code);} while(0)

#define EPILOG EXIT(0)

#ifndef CODEGEN_H
#define CODEGEN_H

void codegen();

#endif